# Site settings
name: 无线通信与多媒体信息处理实验室
title: 无线通信与多媒体信息处理实验室
email: nil
description: "无线通信与多媒体信息处理实验室隶属于中国科学院大学电子电气与通信工程学院。实验室主要从事无线通信系统和图像、视频编解码方向的研究。研究领域包括联合信源信道编译码、联合信道安全编译码，图像、视频处理与传输，全双工通信与网络编码等。实验室承担了多项国家863、973、国家自然科学基金项目，中科院“百人计划”项目等重大科研任务，并与国内外多个科研机构和高新技术企业有重大合作项目。实验室科研人员在各类国际顶级期刊和学术会议发表SCI和EI论文百余篇，申请发明专利数十项。实验室科研力量雄厚，自成立以来，已培养了大批高素质人才。目前，实验室有在读博士、硕士研究生二十余人，其中，实验室培养的博士多选择毕业后到国外顶尖大学继续从事博士后研究，如英国剑桥大学、新加坡南洋理工大学、芬兰坦佩雷大学等；毕业生也多就职于业内顶尖科技企业、科研机构及事业单位，遍布通信、IT乃至金融等各个领域，如美国高通公司、中国移动通信集团、联想研究院、三星研究院、国家开发银行、中国银行等。实验室欢迎敢于迎接挑战、有志于攻读信息与通信工程学科博士、硕士学位的青年学子报考本团队的研究生。 "
baseurl: ""
url: "http://ucase.github.io"

# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:title
permalinks: /blog/:year/:month/:title
